spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update









